### PR TITLE
Hib awad patch 1

### PR DESCRIPTION
**Pull request by HibAwad**

### CODE REVIEW

**Comment by vdmgolub** [comment]
@HibAwad Hello! I noticed that you'd created several PRs with similar changes. May I ask you why? Do you need any help?

**Comment by HibAwad** [comment]
@vdmgolub hello! yes i am trying to these 2 steps on my https://dashboard.infracost.io/org/hibaawad :
Set up one of our [CI/CD integrations](https://www.infracost.io/docs/integrations/cicd/)

Send a pull request to change something in Terraform. This page will refresh automatically when the first pull request data is received.

It seems that there is no pull request for the changes

**Comment by vdmgolub** [comment]
@HibAwad Oh, I see. I think I understand what's going on:

1. You forked this repo and made the changes there.
2. You're trying to create a new PR in hopes that it will run the CLI.

However, the problem is that you're creating a pull request where the base repo is not your fork but the one that belongs to Infracost. It doesn't have `INFRACOST_API_KEY` set up, and for security reasons, the workflow won't run.

To fix that, you need to create a PR for your fork. Here are screenshots how to do it:

Notice the "base repository" is `infracost/example-terraform`:
image

We need to change it to your repo:
image

Can you try to do that?

**Comment by vdmgolub** [comment]
Here's the link to try that https://github.com/HibAwad/example-terraform/compare/HibAwad:master...HibAwad:HibAwad-patch-1?expand=1

**Comment by HibAwad** [comment]
@vdmgolub I tried it and it is not working: 

Run infracost breakdown --path=${TF_ROOT} \
Error: No such file or directory examples/terraform-project/code

Try setting --path to a Terraform plan JSON file. See https://infracost.io/troubleshoot for how to generate this.
Error: Process completed with exit code 1.

**Comment by vdmgolub** [comment]
@HibAwad Looks like `examples/terraform-project/code` directory doesn't exist: the repo doesn't have the `/code` directory. You can try setting it as:
1. `examples/terraform-project` for AWS example
2. `examples/terraform-project/google` for Google Cloud example
3. `examples/terraform-project/azure` for Azure example

**Comment by HibAwad** [comment]
> @HibAwad Looks like `examples/terraform-project/code` directory doesn't exist: the repo doesn't have the `/code` directory. You can try setting the `TF_ROOT` as:
> 
> 1. `examples/terraform-project` for AWS example
> 2. `examples/terraform-project/google` for Google Cloud example
> 3. `examples/terraform-project/azure` for Azure example

still doesn't exist

**Comment by vdmgolub** [comment]
@HibAwad Sorry, I used the incorrect path in my example. I've updated my comment above. The idea is that you should point the CLI to the directory where your TF code is located.

For your GitHub workflow, it is running in the context of "current directory," so the `TF_ROOT` in this case should be `.` or `./google` or `./azure`.

**Comment by HibAwad** [comment]
Thank you very much for your help

**Pull request closed without merging**
